title: Exoplanet imaging data challenge (Stage 1 - detection)
description: Community-wide data challenge for high-contrast imaging data processing. Main goal -- the fair comparison of algorithms for post-processing high-contrast imaging sequences.
markdown: kramdown
show_downloads: true
git_branch: master
logo_url: https://carlgogo.github.io/exoimaging_challenge/assets/images/challenge_logo_LR.png
google_analytics: UA-84473187-3
google_cse_token:
use_prose_io: true
custom_head: false
custom_sidebar: false
custom_footer: false

author :
  name : Carlos Alberto Gomez Gonzalez
  email : carlosgg33@gmail.com
  github : carlgogo

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed

theme:
wiki_folder: wiki
use_github_wiki: false